#!/usr/bin/env python3
"""Generate the immutable Alembic initial SQL from ordered Flyway sources."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

MIGRATIONS = (
    "V1__init_schema.sql",
    "V20260722__add_interview_category_to_interview_sessions.sql",
    "V20260723__ensure_pgvector_store.sql",
    "V20260724__add_question_gen_status.sql",
    "V20260803__add_interview_request_id.sql",
)


def build_document(root: Path) -> str:
    source_root = root / "app/src/main/resources/db/migration"
    sections = [
        "-- Generated by migration/scripts/sync-flyway-schema.py.",
        "-- Do not edit manually; Flyway SQL remains the migration source of truth.",
        "",
    ]
    for filename in MIGRATIONS:
        path = source_root / filename
        content = path.read_text(encoding="utf-8").strip()
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        sections.extend(
            [
                f"-- BEGIN {filename} sha256={digest}",
                content,
                f"-- END {filename}",
                "",
            ]
        )
    return "\n".join(sections)


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    output = root / "backend/alembic/sql/0001_initial_schema.sql"
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = build_document(root)
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.exists() else ""
        if actual != expected:
            raise SystemExit(
                "backend/alembic/sql/0001_initial_schema.sql is stale; "
                "run ./migration/scripts/sync-flyway-schema.py"
            )
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
