--
-- PostgreSQL database dump
--

\restrict bzoX9Qyi5bc55mEOFSDZSxAi3E9JSoI26XAhBEn07DXbdU3joMrK6hxtdcGH2Ec

-- Dumped from database version 16.12 (Debian 16.12-1.pgdg12+1)
-- Dumped by pg_dump version 16.12 (Debian 16.12-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: interview_answers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_answers (
    id bigint NOT NULL,
    answered_at timestamp(6) without time zone NOT NULL,
    category character varying(255),
    feedback text,
    key_points_json text,
    question text,
    question_index integer,
    reference_answer text,
    score integer,
    user_answer text,
    session_id bigint NOT NULL
);


--
-- Name: interview_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_schedule (
    id bigint NOT NULL,
    company_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    interview_time timestamp(6) without time zone NOT NULL,
    interview_type character varying(255),
    interviewer character varying(255),
    meeting_link text,
    notes text,
    "position" character varying(255) NOT NULL,
    round_number integer,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT interview_schedule_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'RESCHEDULED'::character varying])::text[])))
);


--
-- Name: interview_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_sessions (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    current_question_index integer,
    difficulty character varying(16),
    evaluate_error character varying(500),
    evaluate_status character varying(20),
    improvements_json text,
    interview_category character varying(64),
    knowledge_base_id bigint,
    llm_provider character varying(50),
    overall_feedback text,
    overall_score integer,
    questions_json text,
    reference_answers_json text,
    resume_id bigint,
    session_id character varying(36) NOT NULL,
    skill_id character varying(64),
    source_type character varying(32),
    status character varying(20),
    strengths_json text,
    total_questions integer,
    request_id character varying(64),
    CONSTRAINT interview_sessions_evaluate_status_check CHECK (((evaluate_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT interview_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'EVALUATED'::character varying])::text[])))
);


--
-- Name: COLUMN interview_sessions.interview_category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.interview_sessions.interview_category IS '知识库面试方向（来自题库 category，普通面试为 NULL）';


--
-- Name: interview_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_base_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_base_questions (
    id bigint NOT NULL,
    category character varying(64),
    created_at timestamp(6) without time zone NOT NULL,
    difficulty character varying(16),
    follow_ups_json text,
    kb_content_hash character varying(64),
    key_points_json text,
    knowledge_base_id bigint,
    question text NOT NULL,
    reference_answer text,
    scoring_rubric text,
    skill_id character varying(64) NOT NULL,
    source_context text,
    status character varying(20) NOT NULL,
    topic_summary character varying(300),
    type character varying(64),
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT knowledge_base_questions_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'ARCHIVED'::character varying, 'STALE'::character varying])::text[])))
);


--
-- Name: knowledge_base_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_base_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_base_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_bases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_bases (
    id bigint NOT NULL,
    access_count integer,
    category character varying(100),
    chunk_count integer,
    content_type character varying(255),
    file_hash character varying(64) NOT NULL,
    file_size bigint,
    last_accessed_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    original_filename character varying(255) NOT NULL,
    question_count integer,
    storage_key character varying(500),
    storage_url character varying(1000),
    uploaded_at timestamp(6) without time zone NOT NULL,
    vector_error character varying(500),
    vector_status character varying(20),
    question_gen_status character varying(20) DEFAULT 'NONE'::character varying NOT NULL,
    question_gen_error character varying(500),
    question_gen_task_id character varying(36),
    question_gen_config text,
    question_gen_message character varying(500),
    question_gen_saved_count integer DEFAULT 0 NOT NULL,
    question_gen_skipped_count integer DEFAULT 0 NOT NULL,
    question_gen_updated_at timestamp(6) without time zone,
    CONSTRAINT knowledge_bases_question_gen_status_check CHECK (((question_gen_status)::text = ANY ((ARRAY['NONE'::character varying, 'QUEUED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT knowledge_bases_vector_status_check CHECK (((vector_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: knowledge_bases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_bases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_bases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: llm_global_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.llm_global_setting (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    default_chat_provider_id character varying(64) NOT NULL,
    default_embedding_provider_id character varying(64) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: llm_provider_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.llm_provider_config (
    id character varying(64) NOT NULL,
    api_key_ciphertext character varying(4096) NOT NULL,
    api_key_nonce character varying(64) NOT NULL,
    base_url character varying(512) NOT NULL,
    builtin boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    embedding_dimensions integer,
    embedding_model character varying(128),
    enabled boolean NOT NULL,
    model character varying(128) NOT NULL,
    supports_embedding boolean NOT NULL,
    temperature double precision,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: rag_chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rag_chat_messages (
    id bigint NOT NULL,
    completed boolean,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message_order integer NOT NULL,
    type character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    session_id bigint NOT NULL,
    CONSTRAINT rag_chat_messages_type_check CHECK (((type)::text = ANY ((ARRAY['USER'::character varying, 'ASSISTANT'::character varying])::text[])))
);


--
-- Name: rag_chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rag_chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rag_chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rag_chat_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rag_chat_sessions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_pinned boolean DEFAULT false,
    message_count integer,
    status character varying(20),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT rag_chat_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ARCHIVED'::character varying])::text[])))
);


--
-- Name: rag_chat_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rag_chat_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rag_chat_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rag_session_knowledge_bases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rag_session_knowledge_bases (
    session_id bigint NOT NULL,
    knowledge_base_id bigint NOT NULL
);


--
-- Name: resume_analyses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resume_analyses (
    id bigint NOT NULL,
    analyzed_at timestamp(6) without time zone NOT NULL,
    content_score integer,
    expression_score integer,
    overall_score integer,
    project_score integer,
    skill_match_score integer,
    strengths_json text,
    structure_score integer,
    suggestions_json text,
    summary text,
    resume_id bigint NOT NULL
);


--
-- Name: resume_analyses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resume_analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_analyses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resumes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resumes (
    id bigint NOT NULL,
    access_count integer,
    analyze_error character varying(500),
    analyze_status character varying(20),
    content_type character varying(255),
    file_hash character varying(64) NOT NULL,
    file_size bigint,
    last_accessed_at timestamp(6) without time zone,
    original_filename character varying(255) NOT NULL,
    resume_text text,
    storage_key character varying(500),
    storage_url character varying(1000),
    uploaded_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT resumes_analyze_status_check CHECK (((analyze_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: resumes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vector_store; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vector_store (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    content text,
    metadata json,
    embedding public.vector(1024)
);


--
-- Name: voice_interview_evaluations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_interview_evaluations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    improvements_json text,
    interview_date timestamp(6) without time zone,
    interviewer_role character varying(255),
    overall_feedback text,
    overall_score integer,
    question_evaluations_json text,
    reference_answers_json text,
    session_id bigint,
    strengths_json text
);


--
-- Name: voice_interview_evaluations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.voice_interview_evaluations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voice_interview_evaluations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voice_interview_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_interview_messages (
    id bigint NOT NULL,
    ai_generated_text text,
    created_at timestamp(6) without time zone,
    message_type character varying(255) NOT NULL,
    phase character varying(255),
    sequence_num integer,
    session_id bigint,
    "timestamp" timestamp(6) without time zone,
    user_recognized_text text,
    CONSTRAINT voice_interview_messages_phase_check CHECK (((phase)::text = ANY ((ARRAY['INTRO'::character varying, 'TECH'::character varying, 'PROJECT'::character varying, 'HR'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: voice_interview_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.voice_interview_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voice_interview_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voice_interview_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voice_interview_sessions (
    id bigint NOT NULL,
    actual_duration integer,
    created_at timestamp(6) without time zone,
    current_phase character varying(255),
    custom_jd_text text,
    difficulty character varying(16),
    end_time timestamp(6) without time zone,
    evaluate_error character varying(500),
    evaluate_status character varying(255),
    hr_enabled boolean,
    intro_enabled boolean,
    llm_provider character varying(50),
    paused_at timestamp(6) without time zone,
    planned_duration integer,
    project_enabled boolean,
    resume_id bigint,
    resumed_at timestamp(6) without time zone,
    role_type character varying(255) NOT NULL,
    skill_id character varying(64),
    start_time timestamp(6) without time zone,
    status character varying(255),
    tech_enabled boolean,
    updated_at timestamp(6) without time zone,
    user_id character varying(255),
    CONSTRAINT voice_interview_sessions_current_phase_check CHECK (((current_phase)::text = ANY ((ARRAY['INTRO'::character varying, 'TECH'::character varying, 'PROJECT'::character varying, 'HR'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT voice_interview_sessions_evaluate_status_check CHECK (((evaluate_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT voice_interview_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: voice_interview_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.voice_interview_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voice_interview_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: knowledge_bases idx_kb_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_bases
    ADD CONSTRAINT idx_kb_hash UNIQUE (file_hash);


--
-- Name: resumes idx_resume_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT idx_resume_hash UNIQUE (file_hash);


--
-- Name: interview_answers interview_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_answers
    ADD CONSTRAINT interview_answers_pkey PRIMARY KEY (id);


--
-- Name: interview_schedule interview_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_schedule
    ADD CONSTRAINT interview_schedule_pkey PRIMARY KEY (id);


--
-- Name: interview_sessions interview_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_pkey PRIMARY KEY (id);


--
-- Name: knowledge_base_questions knowledge_base_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base_questions
    ADD CONSTRAINT knowledge_base_questions_pkey PRIMARY KEY (id);


--
-- Name: knowledge_bases knowledge_bases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_bases
    ADD CONSTRAINT knowledge_bases_pkey PRIMARY KEY (id);


--
-- Name: llm_global_setting llm_global_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.llm_global_setting
    ADD CONSTRAINT llm_global_setting_pkey PRIMARY KEY (id);


--
-- Name: llm_provider_config llm_provider_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.llm_provider_config
    ADD CONSTRAINT llm_provider_config_pkey PRIMARY KEY (id);


--
-- Name: rag_chat_messages rag_chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rag_chat_messages
    ADD CONSTRAINT rag_chat_messages_pkey PRIMARY KEY (id);


--
-- Name: rag_chat_sessions rag_chat_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rag_chat_sessions
    ADD CONSTRAINT rag_chat_sessions_pkey PRIMARY KEY (id);


--
-- Name: rag_session_knowledge_bases rag_session_knowledge_bases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rag_session_knowledge_bases
    ADD CONSTRAINT rag_session_knowledge_bases_pkey PRIMARY KEY (session_id, knowledge_base_id);


--
-- Name: resume_analyses resume_analyses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_analyses
    ADD CONSTRAINT resume_analyses_pkey PRIMARY KEY (id);


--
-- Name: resumes resumes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_pkey PRIMARY KEY (id);


--
-- Name: interview_sessions uk42bhenf7mu90ochoc1efpg3xa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT uk42bhenf7mu90ochoc1efpg3xa UNIQUE (session_id);


--
-- Name: interview_answers uk_interview_answer_session_question; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_answers
    ADD CONSTRAINT uk_interview_answer_session_question UNIQUE (session_id, question_index);


--
-- Name: voice_interview_evaluations ukijx8aelak8vqf9n4to88qqrna; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_interview_evaluations
    ADD CONSTRAINT ukijx8aelak8vqf9n4to88qqrna UNIQUE (session_id);


--
-- Name: vector_store vector_store_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vector_store
    ADD CONSTRAINT vector_store_pkey PRIMARY KEY (id);


--
-- Name: voice_interview_evaluations voice_interview_evaluations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_interview_evaluations
    ADD CONSTRAINT voice_interview_evaluations_pkey PRIMARY KEY (id);


--
-- Name: voice_interview_messages voice_interview_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_interview_messages
    ADD CONSTRAINT voice_interview_messages_pkey PRIMARY KEY (id);


--
-- Name: voice_interview_sessions voice_interview_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voice_interview_sessions
    ADD CONSTRAINT voice_interview_sessions_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_interview_answer_session_question; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_answer_session_question ON public.interview_answers USING btree (session_id, question_index);


--
-- Name: idx_interview_session_resume_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_session_resume_created ON public.interview_sessions USING btree (resume_id, created_at);


--
-- Name: idx_interview_session_resume_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_session_resume_status_created ON public.interview_sessions USING btree (resume_id, status, created_at);


--
-- Name: idx_interview_session_skill_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_session_skill_created ON public.interview_sessions USING btree (skill_id, created_at);


--
-- Name: idx_kb_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_category ON public.knowledge_bases USING btree (category);


--
-- Name: idx_kb_question_gen_status_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_question_gen_status_updated ON public.knowledge_bases USING btree (question_gen_status, question_gen_updated_at);


--
-- Name: idx_kb_question_kb_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_question_kb_status ON public.knowledge_base_questions USING btree (knowledge_base_id, status);


--
-- Name: idx_kb_question_skill_difficulty; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kb_question_skill_difficulty ON public.knowledge_base_questions USING btree (skill_id, difficulty);


--
-- Name: idx_rag_message_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rag_message_order ON public.rag_chat_messages USING btree (session_id, message_order);


--
-- Name: idx_rag_message_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rag_message_session ON public.rag_chat_messages USING btree (session_id);


--
-- Name: idx_rag_session_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rag_session_updated ON public.rag_chat_sessions USING btree (updated_at);


--
-- Name: spring_ai_vector_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX spring_ai_vector_index ON public.vector_store USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: uk_interview_sessions_request_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_interview_sessions_request_id ON public.interview_sessions USING btree (request_id);


--
-- Name: rag_chat_messages fkfohypaygc0qfqo62vyaxlbntn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rag_chat_messages
    ADD CONSTRAINT fkfohypaygc0qfqo62vyaxlbntn FOREIGN KEY (session_id) REFERENCES public.rag_chat_sessions(id);


--
-- Name: interview_sessions fkhresfe6p1s53klvmqhxxissa2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT fkhresfe6p1s53klvmqhxxissa2 FOREIGN KEY (resume_id) REFERENCES public.resumes(id);


--
-- Name: interview_answers fkjeqvvamvdarrcbswn6kkiuym9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_answers
    ADD CONSTRAINT fkjeqvvamvdarrcbswn6kkiuym9 FOREIGN KEY (session_id) REFERENCES public.interview_sessions(id);


--
-- Name: rag_session_knowledge_bases fkjsfwqyt1ntgr0fcvjieq8c0nb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rag_session_knowledge_bases
    ADD CONSTRAINT fkjsfwqyt1ntgr0fcvjieq8c0nb FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_bases(id);


--
-- Name: knowledge_base_questions fkosobqu06r3tbr13ca043slftw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_base_questions
    ADD CONSTRAINT fkosobqu06r3tbr13ca043slftw FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_bases(id);


--
-- Name: rag_session_knowledge_bases fkqfob368wcvb82elsjkx2troqu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rag_session_knowledge_bases
    ADD CONSTRAINT fkqfob368wcvb82elsjkx2troqu FOREIGN KEY (session_id) REFERENCES public.rag_chat_sessions(id);


--
-- Name: resume_analyses fkrp4f11h23bp0j118yan185lr5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resume_analyses
    ADD CONSTRAINT fkrp4f11h23bp0j118yan185lr5 FOREIGN KEY (resume_id) REFERENCES public.resumes(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bzoX9Qyi5bc55mEOFSDZSxAi3E9JSoI26XAhBEn07DXbdU3joMrK6hxtdcGH2Ec

