-- Current application schema.

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE interview_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6),
  interview_time TIMESTAMP(6) NOT NULL,
  interview_type VARCHAR(255),
  interviewer VARCHAR(255),
  meeting_link TEXT,
  notes TEXT,
  "position" VARCHAR(255) NOT NULL,
  round_number INTEGER,
  status VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT interview_schedule_status_check
    CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'RESCHEDULED'))
);

CREATE TABLE resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_count INTEGER,
  analyze_error VARCHAR(500),
  analyze_status VARCHAR(20),
  content_type VARCHAR(255),
  file_hash VARCHAR(64) NOT NULL,
  file_size BIGINT,
  last_accessed_at TIMESTAMP(6),
  original_filename VARCHAR(255) NOT NULL,
  resume_text TEXT,
  storage_key VARCHAR(500),
  storage_url VARCHAR(1000),
  uploaded_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT resumes_analyze_status_check
    CHECK (analyze_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT idx_resume_hash UNIQUE (file_hash)
);

CREATE TABLE resume_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analyzed_at TIMESTAMP(6) NOT NULL,
  content_score INTEGER,
  expression_score INTEGER,
  overall_score INTEGER,
  project_score INTEGER,
  skill_match_score INTEGER,
  strengths_json TEXT,
  structure_score INTEGER,
  suggestions_json TEXT,
  summary TEXT,
  resume_id BIGINT NOT NULL,
  CONSTRAINT fkrp4f11h23bp0j118yan185lr5
    FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

CREATE TABLE interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  context_json TEXT,
  current_question_id UUID,
  difficulty VARCHAR(16),
  evaluate_error VARCHAR(500),
  evaluate_status VARCHAR(20),
  improvements_json TEXT,
  interview_category VARCHAR(64),
  knowledge_base_id BIGINT,
  llm_provider VARCHAR(50),
  max_follow_ups_per_main INTEGER NOT NULL,
  overall_feedback TEXT,
  overall_score INTEGER,
  planned_main_question_count INTEGER NOT NULL,
  reference_answers_json TEXT,
  request_id VARCHAR(64),
  resume_id BIGINT,
  session_id VARCHAR(36) NOT NULL,
  skill_id VARCHAR(64),
  status VARCHAR(20),
  strengths_json TEXT,
  CONSTRAINT interview_sessions_channel_check
    CHECK (channel IN ('TEXT', 'KNOWLEDGE_BASE', 'VOICE')),
  CONSTRAINT interview_sessions_evaluate_status_check
    CHECK (evaluate_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT interview_sessions_status_check
    CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'EVALUATED')),
  CONSTRAINT uk42bhenf7mu90ochoc1efpg3xa UNIQUE (session_id),
  CONSTRAINT fkhresfe6p1s53klvmqhxxissa2
    FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

COMMENT ON COLUMN interview_sessions.interview_category
  IS '知识库面试方向（来自题库 category，普通面试为 NULL）';

CREATE TABLE interview_questions (
  id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),
  interview_session_id BIGINT NOT NULL,
  kind VARCHAR(16) NOT NULL,
  phase VARCHAR(16),
  main_order INTEGER NOT NULL,
  follow_up_order INTEGER NOT NULL,
  parent_question_id UUID,
  question TEXT NOT NULL,
  type VARCHAR(64) NOT NULL,
  category VARCHAR(255),
  topic_summary VARCHAR(500),
  reference_answer TEXT,
  key_points_json TEXT,
  scoring_rubric TEXT,
  source_context TEXT,
  source_question_id BIGINT,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_interview_questions_session
    FOREIGN KEY (interview_session_id)
    REFERENCES interview_sessions(id) ON DELETE CASCADE,
  CONSTRAINT uk_interview_question_order
    UNIQUE (interview_session_id, main_order, follow_up_order),
  CONSTRAINT uk_interview_question_id_session
    UNIQUE (id, interview_session_id),
  CONSTRAINT fk_interview_question_parent_session
    FOREIGN KEY (parent_question_id, interview_session_id)
    REFERENCES interview_questions(id, interview_session_id)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT interview_questions_kind_check CHECK (
    (kind = 'MAIN' AND parent_question_id IS NULL AND follow_up_order = 0)
    OR
    (kind = 'FOLLOW_UP' AND parent_question_id IS NOT NULL AND follow_up_order >= 1)
  )
);

ALTER TABLE interview_sessions
  ADD CONSTRAINT fk_interview_sessions_current_question
  FOREIGN KEY (current_question_id) REFERENCES interview_questions(id);

CREATE TABLE interview_turns (
  id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),
  interview_session_id BIGINT NOT NULL,
  question_id UUID NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  answer TEXT,
  answer_hash VARCHAR(64) NOT NULL,
  action VARCHAR(16),
  acknowledgement VARCHAR(200),
  next_question_id UUID,
  decision_reason VARCHAR(500),
  reason_code VARCHAR(64),
  target_topic VARCHAR(128),
  confidence DOUBLE PRECISION,
  decision_status VARCHAR(16) NOT NULL,
  provider_id VARCHAR(64),
  model_name VARCHAR(255),
  prompt_version VARCHAR(32),
  schema_version VARCHAR(32),
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  total_tokens INTEGER,
  decision_duration_ms INTEGER,
  error VARCHAR(500),
  processing_started_at TIMESTAMP(6) NOT NULL,
  lease_expires_at TIMESTAMP(6) NOT NULL,
  answered_at TIMESTAMP(6) NOT NULL,
  decided_at TIMESTAMP(6),
  CONSTRAINT fk_interview_turns_session
    FOREIGN KEY (interview_session_id)
    REFERENCES interview_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_interview_turns_question
    FOREIGN KEY (question_id) REFERENCES interview_questions(id),
  CONSTRAINT fk_interview_turns_next_question
    FOREIGN KEY (next_question_id) REFERENCES interview_questions(id),
  CONSTRAINT uk_interview_turn_request
    UNIQUE (interview_session_id, request_id),
  CONSTRAINT uk_interview_turn_question
    UNIQUE (interview_session_id, question_id),
  CONSTRAINT interview_turns_status_check
    CHECK (decision_status IN ('PROCESSING', 'COMPLETED', 'FALLBACK', 'FAILED')),
  CONSTRAINT interview_turns_action_check
    CHECK (action IS NULL OR action IN ('FOLLOW_UP', 'NEXT_MAIN', 'COMPLETE'))
);

CREATE TABLE knowledge_bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_count INTEGER,
  category VARCHAR(100),
  chunk_count INTEGER,
  content_type VARCHAR(255),
  file_hash VARCHAR(64) NOT NULL,
  file_size BIGINT,
  last_accessed_at TIMESTAMP(6),
  name VARCHAR(255) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  question_count INTEGER,
  question_gen_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
  question_gen_error VARCHAR(500),
  question_gen_task_id VARCHAR(36),
  question_gen_config TEXT,
  question_gen_message VARCHAR(500),
  question_gen_saved_count INTEGER NOT NULL DEFAULT 0,
  question_gen_skipped_count INTEGER NOT NULL DEFAULT 0,
  question_gen_updated_at TIMESTAMP(6),
  storage_key VARCHAR(500),
  storage_url VARCHAR(1000),
  uploaded_at TIMESTAMP(6) NOT NULL,
  vector_error VARCHAR(500),
  vector_status VARCHAR(20),
  CONSTRAINT knowledge_bases_question_gen_status_check
    CHECK (question_gen_status IN ('NONE', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT knowledge_bases_vector_status_check
    CHECK (vector_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT idx_kb_hash UNIQUE (file_hash)
);

CREATE TABLE knowledge_base_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(64),
  created_at TIMESTAMP(6) NOT NULL,
  difficulty VARCHAR(16),
  follow_ups_json TEXT,
  kb_content_hash VARCHAR(64),
  key_points_json TEXT,
  knowledge_base_id BIGINT,
  question TEXT NOT NULL,
  reference_answer TEXT,
  scoring_rubric TEXT,
  skill_id VARCHAR(64) NOT NULL,
  source_context TEXT,
  status VARCHAR(20) NOT NULL,
  topic_summary VARCHAR(300),
  type VARCHAR(64),
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT knowledge_base_questions_status_check
    CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED', 'STALE')),
  CONSTRAINT fkosobqu06r3tbr13ca043slftw
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id)
);

CREATE TABLE llm_provider_config (
  id VARCHAR(64) PRIMARY KEY,
  api_key_ciphertext VARCHAR(4096) NOT NULL,
  api_key_nonce VARCHAR(64) NOT NULL,
  base_url VARCHAR(512) NOT NULL,
  builtin BOOLEAN NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  embedding_dimensions INTEGER,
  embedding_model VARCHAR(128),
  enabled BOOLEAN NOT NULL,
  model VARCHAR(128) NOT NULL,
  supports_embedding BOOLEAN NOT NULL,
  temperature DOUBLE PRECISION,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE llm_global_setting (
  id BIGINT PRIMARY KEY,
  created_at TIMESTAMP(6) NOT NULL,
  default_chat_provider_id VARCHAR(64) NOT NULL,
  default_embedding_provider_id VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE voice_model_config (
  id BIGINT PRIMARY KEY,
  asr_provider_id VARCHAR(64) NOT NULL,
  asr_url VARCHAR(512) NOT NULL,
  asr_model VARCHAR(128) NOT NULL,
  asr_language VARCHAR(32) NOT NULL,
  asr_format VARCHAR(32) NOT NULL,
  asr_sample_rate INTEGER NOT NULL,
  asr_enable_turn_detection BOOLEAN NOT NULL,
  asr_turn_detection_type VARCHAR(64) NOT NULL,
  asr_turn_detection_threshold DOUBLE PRECISION NOT NULL,
  asr_silence_ms INTEGER NOT NULL,
  tts_provider_id VARCHAR(64) NOT NULL,
  tts_url VARCHAR(512) NOT NULL,
  tts_model VARCHAR(128) NOT NULL,
  tts_voice VARCHAR(128) NOT NULL,
  tts_format VARCHAR(32) NOT NULL,
  tts_sample_rate INTEGER NOT NULL,
  tts_mode VARCHAR(32) NOT NULL,
  tts_language_type VARCHAR(32) NOT NULL,
  tts_speech_rate DOUBLE PRECISION NOT NULL,
  tts_volume INTEGER NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_voice_model_config_asr_provider
    FOREIGN KEY (asr_provider_id) REFERENCES llm_provider_config(id),
  CONSTRAINT fk_voice_model_config_tts_provider
    FOREIGN KEY (tts_provider_id) REFERENCES llm_provider_config(id)
);

CREATE TABLE rag_chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6) NOT NULL,
  is_pinned BOOLEAN DEFAULT false,
  message_count INTEGER,
  status VARCHAR(20),
  title VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT rag_chat_sessions_status_check
    CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE rag_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed BOOLEAN,
  content TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  message_order INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP(6),
  session_id BIGINT NOT NULL,
  CONSTRAINT rag_chat_messages_type_check
    CHECK (type IN ('USER', 'ASSISTANT')),
  CONSTRAINT fkfohypaygc0qfqo62vyaxlbntn
    FOREIGN KEY (session_id) REFERENCES rag_chat_sessions(id)
);

CREATE TABLE rag_session_knowledge_bases (
  session_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  PRIMARY KEY (session_id, knowledge_base_id),
  CONSTRAINT fkqfob368wcvb82elsjkx2troqu
    FOREIGN KEY (session_id) REFERENCES rag_chat_sessions(id),
  CONSTRAINT fkjsfwqyt1ntgr0fcvjieq8c0nb
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id)
);

CREATE TABLE vector_store (
  id UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
  content TEXT,
  metadata JSON,
  embedding public.vector(1024)
);

CREATE TABLE voice_interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actual_duration INTEGER,
  created_at TIMESTAMP(6),
  current_phase VARCHAR(255),
  custom_jd_text TEXT,
  difficulty VARCHAR(16),
  end_time TIMESTAMP(6),
  evaluate_error VARCHAR(500),
  evaluate_status VARCHAR(255),
  hr_enabled BOOLEAN,
  intro_enabled BOOLEAN,
  interview_session_id BIGINT NOT NULL,
  llm_provider VARCHAR(50),
  paused_at TIMESTAMP(6),
  planned_duration INTEGER,
  project_enabled BOOLEAN,
  resume_id BIGINT,
  resumed_at TIMESTAMP(6),
  role_type VARCHAR(255) NOT NULL,
  skill_id VARCHAR(64),
  start_time TIMESTAMP(6),
  status VARCHAR(255),
  tech_enabled BOOLEAN,
  updated_at TIMESTAMP(6),
  user_id VARCHAR(255),
  CONSTRAINT voice_interview_sessions_current_phase_check
    CHECK (current_phase IN ('INTRO', 'TECH', 'PROJECT', 'HR', 'COMPLETED')),
  CONSTRAINT voice_interview_sessions_evaluate_status_check
    CHECK (evaluate_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT voice_interview_sessions_status_check
    CHECK (status IN ('IN_PROGRESS', 'PAUSED', 'COMPLETED', 'FAILED')),
  CONSTRAINT fk_voice_interview_sessions_interview
    FOREIGN KEY (interview_session_id)
    REFERENCES interview_sessions(id) ON DELETE CASCADE
);

CREATE TABLE voice_interview_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_generated_text TEXT,
  created_at TIMESTAMP(6),
  interview_turn_id UUID,
  message_type VARCHAR(255) NOT NULL,
  phase VARCHAR(255),
  sequence_num INTEGER,
  session_id BIGINT,
  "timestamp" TIMESTAMP(6),
  user_recognized_text TEXT,
  CONSTRAINT voice_interview_messages_phase_check
    CHECK (phase IN ('INTRO', 'TECH', 'PROJECT', 'HR', 'COMPLETED')),
  CONSTRAINT fk_voice_interview_messages_session
    FOREIGN KEY (session_id)
    REFERENCES voice_interview_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_voice_interview_messages_turn
    FOREIGN KEY (interview_turn_id)
    REFERENCES interview_turns(id) ON DELETE SET NULL
);

CREATE INDEX idx_interview_questions_session_order
  ON interview_questions(interview_session_id, main_order, follow_up_order);
CREATE INDEX idx_interview_session_resume_created
  ON interview_sessions(resume_id, created_at);
CREATE INDEX idx_interview_session_resume_status_created
  ON interview_sessions(resume_id, status, created_at);
CREATE INDEX idx_interview_session_skill_created
  ON interview_sessions(skill_id, created_at);
CREATE UNIQUE INDEX uk_interview_sessions_request_id
  ON interview_sessions(request_id);
CREATE INDEX idx_interview_turns_session_answered
  ON interview_turns(interview_session_id, answered_at);
CREATE INDEX idx_interview_turns_processing_lease
  ON interview_turns(decision_status, lease_expires_at);
CREATE INDEX idx_kb_category ON knowledge_bases(category);
CREATE INDEX idx_kb_question_gen_status_updated
  ON knowledge_bases(question_gen_status, question_gen_updated_at);
CREATE INDEX idx_kb_question_kb_status
  ON knowledge_base_questions(knowledge_base_id, status);
CREATE INDEX idx_kb_question_skill_difficulty
  ON knowledge_base_questions(skill_id, difficulty);
CREATE INDEX idx_rag_message_order
  ON rag_chat_messages(session_id, message_order);
CREATE INDEX idx_rag_message_session ON rag_chat_messages(session_id);
CREATE INDEX idx_rag_session_updated ON rag_chat_sessions(updated_at);
CREATE UNIQUE INDEX uk_voice_interview_sessions_interview
  ON voice_interview_sessions(interview_session_id);
CREATE UNIQUE INDEX uk_voice_interview_messages_turn
  ON voice_interview_messages(interview_turn_id);
CREATE INDEX vector_store_embedding_hnsw_idx
  ON vector_store USING hnsw (embedding public.vector_cosine_ops);
